version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scheduled-web-scraping"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10g3h4ic5m9rz"
s3_prefix = "scheduled-web-scraping"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
