version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gbfdx-web-scraping"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n6mr38q04lhu"
s3_prefix = "gbfdx-web-scraping"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
